name: Deploy to Koyeb

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Koyeb CLI
        run: curl -fsSL https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh

      - name: Add Koyeb CLI to PATH
        run: echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Deploy to Koyeb
        run: koyeb services redeploy elegant-nissie/modul-1-coding-standards
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}